# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test-3.6: &test
    working_directory: ~/repo
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
          name: Install
          command: pip install pytest pytest-cov pylint .

      - run:
          name: Tests
          command: pytest --cov=./src/pydoc_markdown && coverage html

      - run:
          name: Linting
          command: pylint src || true

      - store_artifacts:
          path: .coverage

      - store_artifacts:
          path: htmlcov

  test-3.7:
    <<: *test
    docker:
      - image: python:3.7

  test-3.8:
    <<: *test
    docker:
      - image: python:3.8

  trial-publish:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install nr.shore==0.0.32
      - run: shore --version
      - run: shore verify --tag "$CIRCLE_TAG"
      - run: shore publish pypi -l
      - run: shore publish pypi --test --skip-existing

  publish:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install nr.shore==0.0.32
      - run: shore --version
      - run: shore verify --tag "$CIRCLE_TAG"
      - run: shore publish pypi -l
      - run: shore publish pypi

  deploy-docs:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install . mkdocs
      - run: pydoc-markdown
      - run: mkdocs gh-deploy -f build/docs/mkdocs.yml

workflows:
  version: 2
  test:
    jobs:
      - deploy-docs
      - test-3.6:
          filters: { tags: { only: /.*/ } }
      - test-3.7:
          filters: { tags: { only: /.*/ } }
      - test-3.8:
          filters: { tags: { only: /.*/ } }
      - trial-publish:
          filters: { tags: { only: /.*/ }, branches: { ignore: /.*/ } }
          requires: [ test-3.6, test-3.7, test-3.8 ]
      - publish:
          filters: { tags: { only: /.*/ }, branches: { ignore: /.*/ } }
          requires: [ trial-publish ]
