# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test-3.6: &test
    working_directory: ~/repo
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
          name: Install
          command: pip install pytest pytest-cov pylint .

      - run:
          name: Tests
          command: pytest --cov=./src/pydoc_markdown && coverage html

      - run:
          name: Linting
          command: pylint src || true

      - store_artifacts:
          path: .coverage

      - store_artifacts:
          path: htmlcov

  test-3.8:
    <<: *test
    docker:
      - image: python:3.8

  test-3.7:
    <<: *test
    docker:
      - image: python:3.7

  test-3.5:
    <<: *test
    docker:
      - image: python:3.5

  test-2.7:
    <<: *test
    docker:
      - image: python:2.7

workflows:
  version: 2
  test:
    jobs:
      - test-3.8
      - test-3.7
      - test-3.6
      - test-3.5
